version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=/app/db/app.db
      - APP_ENV=development
    volumes:
      - ./db:/app/db
    restart: unless-stopped